language:
env:
  global:
    - DEPLOY_CONTAINER_NAME=nginx
    - DEPLOY_CONTAINER_WORKNET=worknet
    - DOCKER_ALI_REGISTRY_HANGZHOU=registry.cn-hangzhou.aliyuncs.com
addons:
  ssh_known_hosts:
    - 106.12.80.76
before_install:
  - sudo apt-get install -y sshpass
script:
  # docker build
  - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER .
  # push to docker hub
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  - docker push $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER
  # push to aliyun
  - docker login --username $DOCKER_ALI_USERNAME --password $DOCKER_ALI_PASSWORD $DOCKER_ALI_REGISTRY_HANGZHOU
  - docker tag $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER $DOCKER_ALI_REGISTRY_HANGZHOU/$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_ALI_REGISTRY_HANGZHOU/$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER
after_success:
  - sshpass -p $DEPLOY_HOST_SSH_PASSWORD ssh $DEPLOY_HOST_SSH_USERNAME@$DEPLOY_HOST "docker rm -f Tool-$DEPLOY_CONTAINER_NAME; docker run -itd --name Tool-$DEPLOY_CONTAINER_NAME --network $DEPLOY_CONTAINER_WORKNET -p 80:80 -p 443:443 -p 8080:8080 -p 8081:8081 -p 20011:20011 -p 20010:20010 --restart always $DOCKER_ALI_REGISTRY_HANGZHOU/$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER; echo container Tool-$DEPLOY_CONTAINER_NAME using image $DOCKER_ALI_REGISTRY_HANGZHOU/$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER started ..; exit;"
notifications:
  email:
    recipients:
      - 445172495@qq.com
    on_success: always
    on_failure: always

